language: python
sudo: enabled
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
sudo: enabled
dist: trusty
group: travis_lts
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - make
      - cmake
      - swig
env:
  - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get -qq update
install:
  - pip install setuptools
  - sudo apt-get -qq install libboost1.64-all-dev
script:
  - bash build_linux.sh