language: python
sudo: enabled
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
sudo: enabled
dist: trusty
group: travis_lts
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-5.0
      - make
      - cmake
      - swig
env:
  - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - wget https://ncu.dl.sourceforge.net/project/boost/boost/1.59.0/boost_1_59_0.tar.bz2
  - tar -xjf boost_1_59_0.tar.bz2
  - cd boost_1_59_0
  - ./bootstrap --prefix=/usr
  - ./b2 -j8
  - sudo ./b2 install
  - pip install setuptools
script:
  - bash build_linux.sh