language: python
sudo: enabled
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
sudo: enabled
dist: trusty
group: travis_lts
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - make
      - cmake
      - libboost-dev-all
      - swig
env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - pip install setuptools
script:
  - bash build_linux.sh